service: gat-genthin-christmas-raffle
# requirements
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    
provider:
  name: aws
  runtime: python3.10
  stage: prod
  region: eu-central-1
  
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
        cors: true